### ISSUE TITLE
BNO055 and environmental sensing

### ISSUE THREAD

**Issue by JoshSat** [opencomputeproject/Time-Appliance-Project#12]
Looking for more details on the IMU being used in this application. 

Is it mainly for vibration detection with an accelerometer? 
Is the magnetometer being used to measure the earth's magnetic fields and magnetic fields coming off other components?

thank you.

**Comment by ahmadexp** [comment]
Vibration and shocks are known things that effect the holdover performance. Magnetometer just comes in the package. Perhaps it can be used to monitor magnetic field changes.
