### ISSUE TITLE
Why different USB connectors (mini and micro)?

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#13]
Is there a reason that a mini USB connector (J3, p.3,C5) is used, vs. the micro USB on J4 (p.5,B6)?

The mini USB isn't very common and adds to BOM complexity.

Also, the micro USB connector shows as J4 on the schematic and J2 in the BOM.

**Comment by ahmadexp** [comment]
All the USB ports are removed in the new design. Reason for different times of USB ports was to make the instruction for the technician much easier. Blue Cable (Mini-USB) goes to ..., Red Cable (Micro-USB) does to ...
The UART ports are now available via the PCIe bus

**Comment by wisxxx** [comment]
Nice touch.
