### ISSUE TITLE
Why DFLZ39 Zener diodes for +12V input isolation?

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#14]
The forward voltage drop of +1.2V seems excessive for simple isolation.

**Comment by ahmadexp** [comment]
It will be removed. This was placed when we had the backup power source as well to keep the MAC up during short power cycles/loses

**Comment by AlphaBetaPhi** [comment]
This is removed in the latest revision. Issue will be resolved with the next revision push.
