### ISSUE TITLE
FPGA IP Licensing

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#17]
What are the licensing or royalty arrangements for the FPGA intellectual property?

There appear to be six IP cores from NetTimeLogic in use.

**Comment by ahmadexp** [comment]
The current license with NetTimeLogic allows the use of the bin file. 
Alternatively we are working on a version without the proprietary IPs. Hopefully coming soon.

**Comment by thschaub** [comment]
Exactly, it is allowed to use the IP cores as implemented in the bin file. If you have adaptation proposals which have a common interest we can also check if it make sense to adapt something as part of this binary license.

There are five NetTimeLogic IP Cores as part of the binary license included (PPS Slave, PPS Master, TOD Slave, Adjustable Clock and Signal Timestamper). The "UART to AXI" and "Static config" are included in the licensing of any other IP Core.
Additionally, there are IP Cores included from Xilinx (AXI UART, AXI Memory Mapped to PCI Express, AXI IIC, AXI GPIO etc.) which are under their end user license agreement:
https://www.xilinx.com/content/dam/xilinx/licenses/ip/end-user-license-agreement.pdf

Currently we are checking different options for a version without the proprietary IP.

**Comment by geerlingguy** [comment]
@AlphaBetaPhi - Was there any other update on this or is this issue closed as other options won't be investigated at this time?

**Comment by AlphaBetaPhi** [comment]
Hi @geerlingguy, we are still investigating this. I'll label appropriately.

**Comment by thschaub** [comment]
There will be soon an update about the open source FPGA version.

https://www.opencompute.org/wiki/Time_Appliances_Project
on Mar-23, 2022, there will be a call about Open Time Card FPGA

**Comment by wisxxx** [comment]
Thanks. I see the pinout in 

 

…/Implementation/Xilinx/TimeCard/Constraints/PinoutConstraint.xdc

 

Good info.

**Comment by wisxxx** [comment]
The pinout appears to show that the PCie interface is reduced to one lane. Am I reading it correctly?

**Comment by thschaub** [comment]
> The pinout appears to show that the PCie interface is reduced to one lane. Am I reading it correctly?

Not really related to this topic. 
If you build the open source FPGA project you could see the configuration of the PCIe memory mapped bridge in Vivado. And yes it's only one lane.

**Comment by thschaub** [comment]
Full Open-Source Project including video tutorials available:
https://github.com/opencomputeproject/Time-Appliance-Project/tree/master/Time-Card/FPGA/
