### ISSUE TITLE
Fab documentation

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#19]
What is the core material?

Is there a fab drawing showing outline, hole, and key component dimensions?

**Comment by AlphaBetaPhi** [comment]
Hi @wisxxx,

Thank for your interest in the project. The core/prepreg materials are listed in the layer stack up image found in Time-Card/FAB/V1

**Comment by wisxxx** [comment]
I don't see a core material - only pre-preg (2113).

**Comment by AlphaBetaPhi** [comment]
Hi @wisxxx,

You may use FR4 for this design which allows access to many fab shops to build the time card. Additionally, you may alter the design for another core material if needed by additional changes or tighter requirements to high speed signals.
