### ISSUE TITLE
Not enough info for ordering 

### ISSUE THREAD

**Issue by ErQrYfkrju** [opencomputeproject/Time-Appliance-Project#20]
Just want to know price for ordering on jlpcb.
Gerber files and BOM are present and loaded without problems, but no CPL. So can`t figure out resulting price.
![Screen Shot 2021-08-19 at 03 37 46](https://user-images.githubusercontent.com/65288684/129989901-790a4b8e-b716-4ed2-a82e-a1ab27af608e.png)

**Comment by ahmadexp** [comment]
@AlphaBetaPhi, what is a CPL file?

**Comment by AlphaBetaPhi** [comment]
Hi @ErQrYfkrju,

I have pushed the pick and place assembly files to https://github.com/opencomputeproject/Time-Appliance-Project/tree/master/Time-Card/FAB/V1/ASSEMBLY
