### ISSUE TITLE
Power to pressure sensor and IMU

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#21]
Why is +3.3V_CLEAN connected to VDDIO (pin 1) of the pressure sensor U4 (p. 5,B5)?

Similarly, why is +3.3V connected to VDD (pin 3) of the IMU U8 (p.5,C2)?

**Comment by AlphaBetaPhi** [comment]
Hi @wisxxx,

We have deprecated the initial prototype version which was used as a development board for testing different vendors and clocks.

Please see [beta-v1 schematics](https://github.com/opencomputeproject/Time-Appliance-Project/blob/master/Time-Card/ECAD/Beta-V1/Timingcard_PROJECT_SCHEMATICS_BETA_V1.pdf)

 We will be releasing additional designs which tighten the requirements and improve performance of the device.
