### ISSUE TITLE
FPGA Design Overview Clarifications

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#39]
Ref: "Time-Card/SOM/FPGA/Readme.pdf", section 2.4

- Step 1 says: "Connect the USB/UART to a host PC running Windows." What USB/UART is that?
- Step 4 says: "Change your configuration as you need it..." Aren't the NetTimeLogic cores already configured in the FPGA binaries?

**Comment by thschaub** [comment]
In some versions of the timecard we have an UART (or USB-UART connection). However, the pins are always there in the FPGA design or on the SOM connector.

E.g. Page 4:  
https://github.com/opencomputeproject/Time-Appliance-Project/blob/master/Time-Card/ECAD/Prototype-V0/Timingcard_PROJECT.pdf

In the FPGA Design this are following pins:
#UART1
set_property PACKAGE_PIN P15 [get_ports Uart1TxDat_DatOut]
set_property PACKAGE_PIN P16 [get_ports Uart1RxDat_DatIn]

or on SOM Connector P1B:
B-71 UART_TXD
B-77 UART_RXD

Details about the UART Communication protocol as well as the Windows Tool you can find here:
https://github.com/opencomputeproject/Time-Appliance-Project/tree/master/Time-Card/SOM/FPGA/UCM
