### ISSUE TITLE
FPGA pin assignments for production version

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#46]
What are the pin assignments for the "Version: 0x8003 (Production Version)" FPGA?

They aren't in "Readme_Production.pdf".

**Comment by thschaub** [comment]
It's not planned to have the pin assignment in the "Readme_Production.pdf" and the schematic (and PCB) of this timecard version is currently not published. Therefore no pinout available at the moment.

**Comment by ahmadexp** [comment]
@wisxxx, please try to join our upcoming meeting about opening the FPGA code of the time card
https://www.linkedin.com/feed/update/urn:li:activity:6909908144374652929

**Comment by thschaub** [comment]
Pinout constraint file for the Open Source Production version is available here:
https://github.com/opencomputeproject/Time-Appliance-Project/blob/master/Time-Card/FPGA/Open-Source/Implementation/Xilinx/TimeCard_Production/Constraints/PinoutConstraint.xdc
