### ISSUE TITLE
External atomic clock for laptops & such

### ISSUE THREAD

**Issue by greereer** [opencomputeproject/Time-Appliance-Project#57]
How feasible do you think the following is:

An external solution that enables my computer's (a Dell XPS for example) outgoing packets to be timestamped with a very accurate clock however as you know my stock NIC does not support hardware timestamping nor do I have a PCIe slot.

My proposal:

A NIC with hardware time stamping and built in rubidium oscillator connected to my laptop via USB

The outgoing packets are sent to the NIC to be accurately timestamped before being transmitted

More power could be supplied to the external setup by an additional 5v usb connection

Ideally the only thing the computer would need is downloadable drivers to alter the ptp handling of the computer.

It will require a method of detecting and compensating for changes in latency between the NIC and computer caused by for instance using a different length USB cables/setups.

I would really like to further this idea, if you could let me know what you think I would be very grateful.

**Comment by ahmadexp** [comment]
The closes to your idea can be found on the following link which was done for the raspberry pi.
https://www.cnx-software.com/2021/08/17/raspberry-pi-4-ieee1588-precision-time-protocol-ptp-with-real-time-hat/#:~:text=InnoRoute%20Real%2DTime%20HAT%20adds,enable%20measurement%20and%20control%20systems.
Couple that with a time card and you are good to go.
I will be more than happy to learn more about your application.
