### ISSUE TITLE
seperate utc offset files

### ISSUE THREAD

**Issue by TuxCoder** [opencomputeproject/Time-Appliance-Project#75]
Folowup of a discussion at the ISCPS

I saw that the UTC offset is represented as a seperate file.
But the adjtimex syscall allows you to get/set the offset already.
https://www.man7.org/linux/man-pages/man2/adjtimex.2.html

so the question is, are this two parameters synced and only a second way to obtain / set the offset or are this two separate values?

Best Regard
TuxCoder

**Comment by ahmadexp** [comment]
@jlemon, would you please comment on this.

**Comment by jlemon** [comment]
The parameters unfortunately aren't synced.  Those calls are for the kernel clock, not for the PHC clock.

There doesn't seem to be any current API to set a PHC clock's TAI/UTC offset, perhaps because the assumption is that the PHC only returns one timebase (TAI)?
