### ISSUE TITLE
LED driver enable pulled down

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#77]
Ref: file "Timingcard_PROJECT.pdf", in Time-Card/HW/ECAD/Prototype-V7/ECADv7.7z

The new status LED driver, U6, on sheet 2 of the new schematic has pin 1 ("SDB") pulled to ground through a 100K resistor.

The data sheet description of this pin reads: "Shutdown the chip when pulled low". That would render the driver and LED's useless.

Also, the pulldown is bypass by a 0.1 uF cap. Why?

**Comment by julianstj1** [comment]
This is a good catch. I corrected these issues in V8. I'll close this issue after uploading V8, please re-open if there are any other issues. Thank you!

**Comment by julianstj1** [comment]
Updated in V8 in Experimental HW folder, will close for now.
