### ISSUE TITLE
Request to make TimeCardOS.bit available

### ISSUE THREAD

**Issue by JohnHay** [opencomputeproject/Time-Appliance-Project#98]
Is it possible to make TimeCardOS.bit available?

If Vivado is not available, a way to "bootstrap" a card is to download the .bit file with a firmware downloader like xc3sprog, then reboot so that the PCIe is recognized and then program  Factory_TimeCardOS.bin through the AXI QSPI interface.

That way even the Operating System does not have to be Linux or MS Windows. Currently I'm using TimeCard.bit from the closed source to bootstrap, so it is not a big issue.

**Comment by thschaub** [comment]
The bitstream files for the available Open-Source implementations are now available: 
[commit b22096f](https://github.com/opencomputeproject/Time-Appliance-Project/commit/b22096f427e6ec01ff5e1c719547a2e447580aaf)
